// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class Perfil
{
    public int Id { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Imagen> Imagen { get; set; } = new List<Imagen>();
}